### ISSUE TITLE
StopIteration error during training when logging to CSV.

### ISSUE THREAD

**Issue by KadenMc** [Jwoo5/fairseq-signals#11]
I am receiving a `StopIteration` error when selecting `csv` as the `common.log_format`:
```
File "fairseq_signals/logging/progress_bar.py", line 373, in _log_to_csv
    headers = next(iter(rd))
StopIteration
```

This occurs just after the first log message is made. It appears the CSV reader iterator is empty, where the CSV file presumably has no header and is empty.

Here is the train command used:
```
fairseq-hydra-train \
    task.data=manifest \
    dataset.valid_subset=valid \
    dataset.batch_size=100 \
    dataset.num_workers=30 \
    distributed_training.distributed_world_size=3 \
    checkpoint.save_dir=ckpts/3kg/pretraining \
    checkpoint.save_interval=10 \
    checkpoint.keep_last_epochs=0 \
    common.log_format=csv \
    --config-dir examples/3kg/config/pretraining/ecg_transformer \
    --config-name 3kg
```

It appears that this error only occurs during distributed training. When using `distributed_training.distributed_world_size=1`, training continues without issue and the CSV file is written to as expected. Also, when using distributed training without `common.log_format=csv`, everything works as expected.

It appears that distributed training will sometimes not break due to the `StopIteration` error, however each row is logged to the CSV the same number of times as the world size. Perhaps this is some kind of race condition error?

Although logging occurs in the `train` function in `fairseq_cli/train.py`, perhaps the `is_data_parallel_master` method in `fairseq_signals/trainer.py` could somehow be used to avoid this repeated logging issue. Perhaps this would also fix the `StopIteration` error.

**Comment by KadenMc** [comment]
Upon further experimentation, it appears that this error occurs only when using distributed training. When using `distributed_training.distributed_world_size=1`, training continues without issue and the CSV file is written to as expected.

**Comment by Jwoo5** [comment]
Thanks for reporting this issue.
I updated the repo to fix this error by activating csv logging only for master rank gpu in DDP environments.
Please refer to the recent commit: https://github.com/Jwoo5/fairseq-signals/commit/e7da0572603f32ca27faa7f5ad49658bbdf4ada4.
