### ISSUE TITLE
The error of Pre-train CMSC model

### ISSUE THREAD

**Issue by CSY-siyuan** [Jwoo5/fairseq-signals#12]
When I run `fairseq-hydra-train task.data=clocs/cmsc --config-dir examples/cmsc/config/pretraining/ecg_transformer --config-name cmsc` for Pre-training a new ECG Transformer model, I encounter the `AttributeError: module 'importlib_resources' has no attribute 'is_resource'` issue. How can I resolve this?

**Comment by Jwoo5** [comment]
Sorry for the late reply.
Could you please let me know the full error logs so that I can figure out what code line exactly raises that error?

**Comment by pranavPrakhar** [comment]
This is because 'is_resource' has now been deprecated. It has been replaced by 'is_file'.
importlib_docs: https://docs.python.org/3/library/importlib.resources.html

The issue can be resolved by modifying 'available' function as:
`
def available(self) -> bool:
        try:
            # package = resources.import_module(self.path)
            # ret = files(package).joinpath("__init__.py").is_file()
            package = self.path
            package_module = resources.files(package)
            init_py_resource = package_module / "__init__.py"
            ret = init_py_resource.is_file()
            assert isinstance(ret, bool)
            return ret
        except (ValueError, ModuleNotFoundError):
            return False
`
