### ISSUE TITLE
Data problrm

### ISSUE THREAD

**Issue by DanMerry** [Jwoo5/fairseq-signals#13]
I have another problem, How to load the data of ecg-id using python? 
![image](https://github.com/Jwoo5/fairseq-signals/assets/52539280/2a223248-2abb-4aec-ac46-73f547eabd38)

**Comment by Jwoo5** [comment]
Sorry for the late reply.
You can load ecg-id data by using simple python code lines as follows:
```
import wfdb
record = wfdb.rdrecord("rec_1")
annot = wfdb.rdann("rec_1", "atr")
```
Note that raw ECG signal values are stored in `record.__dict__["p_signal"]`, and the first index (`record.__dict__["p_signal"][:, 0]`) is for a raw signal and the second index (`record.__dict__["p_signal"][:, 1]`) is for a filtered signal.

**Comment by DanMerry** [comment]
ths very much
